
import { Game, Story, UpcomingGame } from './types';

// Helper for real steam images (Akamai CDN) - High Quality Vertical Library Assets
const getSteamImage = (id: string) => `https://cdn.akamai.steamstatic.com/steam/apps/${id}/library_600x900.jpg`;

// System Requirements Templates
const SPECS_ULTRA = { os: 'Windows 11', processor: 'i9-14900K / Ryzen 9 7950X', memory: '32 GB RAM', graphics: 'RTX 4090 / RX 7900 XTX', storage: '150 GB NVMe SSD' };
const SPECS_HIGH = { os: 'Windows 10/11', processor: 'i7-13700K / Ryzen 7 7800X3D', memory: '32 GB RAM', graphics: 'RTX 4070 / RX 7800 XT', storage: '100 GB SSD' };
const SPECS_MID = { os: 'Windows 10', processor: 'i5-12400F / Ryzen 5 5600X', memory: '16 GB RAM', graphics: 'RTX 3060 / RX 6700 XT', storage: '80 GB SSD' };
const SPECS_LOW = { os: 'Windows 10', processor: 'i5-9400F / Ryzen 5 3600', memory: '16 GB RAM', graphics: 'GTX 1660 Super', storage: '60 GB HDD' };

export const STORIES: Story[] = [
  {
    id: 'story-1',
    title: 'New Arrivals',
    thumbnail: getSteamImage('2246340'), // Monster Hunter Wilds
    image: getSteamImage('2246340'), 
    type: 'image',
    viewed: false
  },
  {
    id: 'story-2',
    title: 'Best Sellers',
    thumbnail: getSteamImage('2358720'), // Black Myth Wukong
    image: getSteamImage('2358720'),
    type: 'image',
    viewed: false
  },
  {
    id: 'story-3',
    title: 'Flash Sale',
    thumbnail: getSteamImage('1551360'), // Forza Horizon 5
    image: getSteamImage('1551360'),
    type: 'image',
    viewed: false
  },
  {
    id: 'story-4',
    title: 'Pre-Orders',
    thumbnail: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co83i0.jpg', // GTA VI
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co83i0.jpg', 
    type: 'image',
    viewed: false
  }
];

export const GAMES: Game[] = [
  // --- 2025 & LATE 2024 RELEASES (THE NEWEST) ---
  {
    id: 'monster_hunter_wilds',
    title: 'Monster Hunter Wilds',
    price: 3499,
    originalPrice: 4999,
    discount: 30,
    rating: 5.0,
    image: getSteamImage('2246340'),
    video: 'https://www.youtube.com/embed/Kind_vK6i9o',
    platform: 'Steam',
    genre: 'Action RPG',
    releaseDate: '2025-02-28',
    players: 'Co-op',
    description: 'PRE-ORDER. The next generation of hunting action. Explore untamed wilds and battle massive monsters.',
    systemReq: SPECS_HIGH,
    reviews: [],
    isNew: true
  },
  {
    id: 'kingdom_come_2',
    title: 'Kingdom Come: Deliverance II',
    price: 2999,
    originalPrice: 4499,
    discount: 33,
    rating: 4.8,
    image: getSteamImage('1771300'),
    video: 'https://www.youtube.com/embed/Z52fI8t5Fk0',
    platform: 'Steam',
    genre: 'RPG',
    releaseDate: '2025-02-11',
    players: 'Single-player',
    description: 'A thrilling story-driven action RPG, set amidst the chaos of a civil war in 15th Century Bohemia.',
    systemReq: SPECS_HIGH,
    reviews: [],
    isNew: true
  },
  {
    id: 'assassins_creed_shadows',
    title: 'Assassin\'s Creed Shadows',
    price: 3999,
    originalPrice: 5999,
    discount: 33,
    rating: 4.7,
    image: 'https://image.api.playstation.com/vulcan/ap/rnd/202405/1410/c02f02677f50275293297097727039656209560375626262.png',
    video: 'https://www.youtube.com/embed/vovkzbtYBC8',
    platform: 'Ubisoft',
    genre: 'Action RPG',
    releaseDate: '2025-02-14',
    players: 'Single-player',
    description: 'Live the intertwined stories of Naoe, an adept shinobi Assassin, and Yasuke, a legendary samurai.',
    systemReq: SPECS_HIGH,
    reviews: [],
    isNew: true
  },
  {
    id: 'avowed',
    title: 'Avowed',
    price: 3499,
    originalPrice: 4999,
    discount: 30,
    rating: 4.5,
    image: getSteamImage('2457220'),
    video: 'https://www.youtube.com/embed/W1Zp2F1qS74',
    platform: 'Steam',
    genre: 'RPG',
    releaseDate: '2025-02-18',
    players: 'Single-player',
    description: 'Explore the Living Lands, a mysterious island filled with adventure and danger.',
    systemReq: SPECS_HIGH,
    reviews: [],
    isNew: true
  },
  {
    id: 'cod_bo6',
    title: 'Call of Duty®: Black Ops 6',
    price: 3999,
    originalPrice: 5599,
    discount: 28,
    rating: 4.6,
    image: getSteamImage('2933620'),
    video: 'https://www.youtube.com/embed/6w9q4z9Z2kE',
    platform: 'BattleNet',
    genre: 'FPS',
    releaseDate: '2024-10-25',
    players: 'Multiplayer',
    description: 'Forced to go rogue. Hunted from within. This is Black Ops 6.',
    systemReq: SPECS_HIGH,
    reviews: [],
    isNew: true
  },
  {
    id: 'dragon_age_veilguard',
    title: 'Dragon Age™: The Veilguard',
    price: 2999,
    originalPrice: 4799,
    discount: 37,
    rating: 4.4,
    image: getSteamImage('1845910'),
    video: 'https://www.youtube.com/embed/4F3N4l-C7qI',
    platform: 'Steam',
    genre: 'RPG',
    releaseDate: '2024-10-31',
    players: 'Single-player',
    description: 'Enter the world of Thedas, a vibrant land of rugged wilderness and treacherous labyrinths.',
    systemReq: SPECS_HIGH,
    reviews: [],
    isNew: true
  },
  {
    id: 'silent_hill_2',
    title: 'SILENT HILL 2 Remake',
    price: 2799,
    originalPrice: 4299,
    discount: 35,
    rating: 4.9,
    image: getSteamImage('2124490'),
    video: 'https://www.youtube.com/embed/PyTp1o8b1-0',
    platform: 'Steam',
    genre: 'Horror',
    releaseDate: '2024-10-08',
    players: 'Single-player',
    description: 'Having received a letter from his deceased wife, James heads to where they shared so many memories.',
    systemReq: SPECS_HIGH,
    reviews: [],
    isNew: true
  },
  {
    id: 'astro_bot',
    title: 'Astro Bot',
    price: 3499,
    originalPrice: 4999,
    discount: 30,
    rating: 5.0,
    image: 'https://image.api.playstation.com/vulcan/ap/rnd/202405/3023/1c888e235489814429783706132960683606963249053070.png',
    video: 'https://www.youtube.com/embed/f3D5X0T5zV0',
    platform: 'PS5',
    genre: 'Platformer',
    releaseDate: '2024-09-06',
    players: 'Single-player',
    description: 'Join ASTRO in a brand-new, supersized space adventure. The PS5 exclusive of the year.',
    systemReq: SPECS_MID,
    reviews: [],
    isNew: true
  },
  {
    id: 'blackmyth_wukong',
    title: 'Black Myth: Wukong',
    price: 2499,
    originalPrice: 4999,
    discount: 50,
    rating: 5.0,
    image: getSteamImage('2358720'),
    video: 'https://www.youtube.com/embed/1z48-k0a-9Y',
    platform: 'Steam',
    genre: 'Action RPG',
    releaseDate: '2024-08-20',
    players: 'Single-player',
    description: 'Destiny calls. A new legend begins in this journey to the west. Unreal Engine 5 masterpiece.',
    systemReq: SPECS_ULTRA,
    reviews: [],
    isNew: true
  },
  {
    id: 'star_wars_outlaws',
    title: 'Star Wars Outlaws',
    price: 3299,
    originalPrice: 5499,
    discount: 40,
    rating: 4.3,
    image: 'https://cdn1.epicgames.com/offer/e97669b1abd844bc98a80958f602447d/EGS_StarWarsOutlaws_MassiveEntertainment_S2_1200x1600-34a8647895c02f232400e0086780963a',
    video: 'https://www.youtube.com/embed/ymcpwq1ltQc',
    platform: 'Ubisoft',
    genre: 'Open World',
    releaseDate: '2024-08-30',
    players: 'Single-player',
    description: 'Experience the first-ever open world Star Wars game.',
    systemReq: SPECS_HIGH,
    reviews: [],
    isNew: true
  },
  {
    id: 'frostpunk_2',
    title: 'Frostpunk 2',
    price: 1499,
    originalPrice: 2499,
    discount: 40,
    rating: 4.5,
    image: getSteamImage('1601580'),
    video: 'https://www.youtube.com/embed/XqE6y6J8g7U',
    platform: 'Steam',
    genre: 'Strategy',
    releaseDate: '2024-09-20',
    players: 'Single-player',
    description: 'Discover a city-survival game set 30 years after an apocalyptic blizzard ravaged Earth.',
    systemReq: SPECS_MID,
    reviews: [],
    isNew: true
  },
  {
    id: 'elden_ring_shadow',
    title: 'Elden Ring: Shadow of the Erdtree',
    price: 1999,
    originalPrice: 2999,
    discount: 33,
    rating: 5.0,
    image: 'https://image.api.playstation.com/vulcan/ap/rnd/202402/1613/9e4142127264870570882885994270417978255977531742.png',
    video: 'https://www.youtube.com/embed/qLZenOn7WUo',
    platform: 'Steam',
    genre: 'RPG Expansion',
    releaseDate: '2024-06-21',
    players: 'Co-op',
    description: 'The massive expansion to the Game of the Year. Guided by Empyrean Miquella.',
    systemReq: SPECS_MID,
    reviews: [],
    isNew: true
  },
  {
    id: 'ghost_tsushima',
    title: 'Ghost of Tsushima DC',
    price: 1999,
    originalPrice: 3999,
    discount: 50,
    rating: 4.9,
    image: getSteamImage('2215430'),
    video: 'https://www.youtube.com/embed/A5g_08j2dK0',
    platform: 'Steam',
    genre: 'Action',
    releaseDate: '2024-05-16',
    players: 'Single-player',
    description: 'A storm is coming. Venture into a vast open-world samurai adventure on PC.',
    systemReq: SPECS_HIGH,
    reviews: [],
    isNew: true
  },
  {
    id: 'stellar_blade',
    title: 'Stellar Blade',
    price: 3499,
    originalPrice: 4999,
    discount: 30,
    rating: 4.8,
    image: 'https://image.api.playstation.com/vulcan/ap/rnd/202401/2916/410292789128036034107144211029749103399933556066.png',
    video: 'https://www.youtube.com/embed/ayek3ZzWb1E',
    platform: 'PS5',
    genre: 'Action',
    releaseDate: '2024-04-26',
    players: 'Single-player',
    description: 'Reclaim Earth for humankind. Fast-paced combat and stunning visuals.',
    systemReq: SPECS_HIGH,
    reviews: [],
    isNew: true
  },
  {
    id: 'dragons_dogma2',
    title: 'Dragon\'s Dogma 2',
    price: 2999,
    originalPrice: 4999,
    discount: 40,
    rating: 4.6,
    image: getSteamImage('2054970'),
    video: 'https://www.youtube.com/embed/Kind_vK6i9o',
    platform: 'Steam',
    genre: 'Open World RPG',
    releaseDate: '2024-03-22',
    players: 'Single-player',
    description: 'Go forth, Arisen! A grand fantasy adventure awaits in this narrative-driven action RPG.',
    systemReq: SPECS_HIGH,
    reviews: []
  },
  {
    id: 'horizon_fw',
    title: 'Horizon Forbidden West',
    price: 1999,
    originalPrice: 3999,
    discount: 50,
    rating: 4.8,
    image: getSteamImage('2420110'),
    video: 'https://www.youtube.com/embed/Lq594XmpPBg',
    platform: 'Steam',
    genre: 'Open World',
    releaseDate: '2024-03-21',
    players: 'Single-player',
    description: 'Explore distant lands, fight bigger and more awe-inspiring machines.',
    systemReq: SPECS_HIGH,
    reviews: []
  },
  {
    id: 'ff7_rebirth',
    title: 'Final Fantasy VII Rebirth',
    price: 3499,
    originalPrice: 5499,
    discount: 36,
    rating: 4.9,
    image: 'https://image.api.playstation.com/vulcan/ap/rnd/202309/1416/92e4b4f65057069176375375326792336337562095209700.png',
    video: 'https://www.youtube.com/embed/H0f3vE8dK3E',
    platform: 'PS5',
    genre: 'RPG',
    releaseDate: '2024-02-29',
    players: 'Single-player',
    description: 'The Unknown Journey Continues. Cloud Strife and his friends escape Midgar.',
    systemReq: SPECS_HIGH,
    reviews: []
  },
  {
    id: 'helldivers2',
    title: 'HELLDIVERS 2',
    price: 1799,
    originalPrice: 2999,
    discount: 40,
    rating: 4.8,
    image: getSteamImage('553850'),
    video: 'https://www.youtube.com/embed/lrb7F6992PY',
    platform: 'Steam',
    genre: 'Co-op Shooter',
    releaseDate: '2024-02-08',
    players: 'Online Co-op',
    description: 'Join the fight for freedom across a hostile galaxy in this fast, frantic, and ferocious shooter.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'tekken8',
    title: 'TEKKEN 8',
    price: 2499,
    originalPrice: 4199,
    discount: 40,
    rating: 4.8,
    image: getSteamImage('1778820'),
    video: 'https://www.youtube.com/embed/2hPuRQz6IlM',
    platform: 'Steam',
    genre: 'Fighting',
    releaseDate: '2024-01-26',
    players: 'Multiplayer',
    description: 'Fist Meets Fate. The next King of Iron Fist Tournament begins.',
    systemReq: SPECS_HIGH,
    reviews: []
  },
  {
    id: 'palworld',
    title: 'Palworld',
    price: 699,
    originalPrice: 1300,
    discount: 46,
    rating: 4.7,
    image: getSteamImage('1623730'),
    video: 'https://www.youtube.com/embed/O44x4Qj_w8o',
    platform: 'Steam',
    genre: 'Survival',
    releaseDate: '2024-01-19',
    players: 'Multiplayer',
    description: 'Fight, farm, build and work alongside mysterious creatures called "Pals".',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'pop_lost_crown',
    title: 'Prince of Persia: The Lost Crown',
    price: 1499,
    originalPrice: 3499,
    discount: 57,
    rating: 4.8,
    image: getSteamImage('2751000'),
    video: 'https://www.youtube.com/embed/1B1aBq0w0nU',
    platform: 'Ubisoft',
    genre: 'Action Platformer',
    releaseDate: '2024-01-18',
    players: 'Single-player',
    description: 'Dash into a stylish and thrilling action-adventure platformer set in a mythological Persian world.',
    systemReq: SPECS_LOW,
    reviews: []
  },

  // --- 2023 BEST SELLERS ---
  {
    id: 'mw3_2023',
    title: 'Call of Duty®: MW III',
    price: 2999,
    originalPrice: 5999,
    discount: 50,
    rating: 3.5,
    image: getSteamImage('2519060'),
    video: 'https://www.youtube.com/embed/mHDEDDrGYvo',
    platform: 'BattleNet',
    genre: 'FPS',
    releaseDate: '2023-11-10',
    players: 'Multiplayer',
    description: 'Captain Price and Task Force 141 face off against the ultimate threat.',
    systemReq: SPECS_HIGH,
    reviews: []
  },
  {
    id: 'alan_wake_2',
    title: 'Alan Wake 2',
    price: 1999,
    originalPrice: 3999,
    discount: 50,
    rating: 4.9,
    image: 'https://cdn1.epicgames.com/offer/c4763f236d08423eb47b4c3008779c84/EGS_AlanWake2_RemedyEntertainment_S2_1200x1600-c7c8091ddac9f960028143a5b4dc572e',
    video: 'https://www.youtube.com/embed/dlQ3FeNu5Yw',
    platform: 'Epic',
    genre: 'Horror',
    releaseDate: '2023-10-27',
    players: 'Single-player',
    description: 'A psychological horror story filled with intense suspense and unexpected twists.',
    systemReq: SPECS_HIGH,
    reviews: []
  },
  { 
    id: 'spiderman_2_ps5', 
    title: 'Marvel\'s Spider-Man 2', 
    price: 3499, 
    originalPrice: 5999, 
    discount: 41, 
    rating: 4.9, 
    image: 'https://image.api.playstation.com/vulcan/ap/rnd/202306/1219/60eca3ac155247e21850c7d075d01ebf0f3f5dbf19cc2aee.png', 
    video: 'https://www.youtube.com/embed/bgqGdIoa52s', 
    platform: 'PS5', 
    genre: 'Action', 
    releaseDate: '2023-10-20', 
    players: 'Single-player', 
    description: 'Spider-Men, Peter Parker and Miles Morales, return for an exciting new adventure.', 
    systemReq: SPECS_HIGH, 
    reviews: []
  },
  {
    id: 'ac_mirage',
    title: 'Assassin\'s Creed Mirage',
    price: 1199,
    originalPrice: 2499,
    discount: 52,
    rating: 4.5,
    image: 'https://image.api.playstation.com/vulcan/ap/rnd/202305/2419/5e636605553099655655523099663365330366606030999.png',
    video: 'https://www.youtube.com/embed/x55lAlFtXmw',
    platform: 'Ubisoft',
    genre: 'Stealth Action',
    releaseDate: '2023-10-05',
    players: 'Single-player',
    description: 'Experience the story of Basim, a cunning street thief seeking answers and justice.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'fc24',
    title: 'EA SPORTS FC™ 24',
    price: 1299,
    originalPrice: 3499,
    discount: 62,
    rating: 4.0,
    image: getSteamImage('2195250'),
    video: 'https://www.youtube.com/embed/XhP3Xh4LMA8',
    platform: 'Steam',
    genre: 'Sports',
    releaseDate: '2023-09-29',
    players: 'Multiplayer',
    description: 'The next chapter in the world\'s game with HyperMotionV technology.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'cyberpunk_phantom',
    title: 'Cyberpunk 2077: Phantom Liberty',
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    rating: 4.8,
    image: getSteamImage('2138330'),
    video: 'https://www.youtube.com/embed/KF65r59U2_s',
    platform: 'Steam',
    genre: 'Action RPG',
    releaseDate: '2023-09-26',
    players: 'Single-player',
    description: 'A spy-thriller expansion for Cyberpunk 2077. Infiltrate Dogtown.',
    systemReq: SPECS_HIGH,
    reviews: []
  },
  {
    id: 'mk_1',
    title: 'Mortal Kombat 1',
    price: 1899,
    originalPrice: 3999,
    discount: 52,
    rating: 4.5,
    image: getSteamImage('1971870'),
    video: 'https://www.youtube.com/embed/7p1qG7G4rgg',
    platform: 'Steam',
    genre: 'Fighting',
    releaseDate: '2023-09-19',
    players: 'Multiplayer',
    description: 'Discover a reborn Mortal Kombat Universe created by the Fire God Liu Kang.',
    systemReq: SPECS_HIGH,
    reviews: []
  },
  {
    id: 'starfield',
    title: 'Starfield',
    price: 2499,
    originalPrice: 4999,
    discount: 50,
    rating: 4.0,
    image: getSteamImage('1716740'),
    video: 'https://www.youtube.com/embed/kfYEiTdsyas',
    platform: 'Steam',
    genre: 'Space RPG',
    releaseDate: '2023-09-06',
    players: 'Single-player',
    description: 'In this next generation role-playing game set amongst the stars, create any character you want.',
    systemReq: SPECS_HIGH,
    reviews: []
  },
  {
    id: 'armored_core_6',
    title: 'Armored Core VI',
    price: 2399,
    originalPrice: 3999,
    discount: 40,
    rating: 4.8,
    image: getSteamImage('1888160'),
    video: 'https://www.youtube.com/embed/K_F5bFk2XoY',
    platform: 'Steam',
    genre: 'Mech Action',
    releaseDate: '2023-08-25',
    players: 'Multiplayer',
    description: 'A new action game based on the concept of the ARMORED CORE series.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'bg3',
    title: 'Baldur\'s Gate 3',
    price: 2499,
    originalPrice: 3599,
    discount: 30,
    rating: 5.0,
    image: getSteamImage('1086940'),
    video: 'https://www.youtube.com/embed/OcP0WdH7rTs',
    platform: 'Steam',
    genre: 'CRPG',
    releaseDate: '2023-08-03',
    players: 'Co-op',
    description: 'Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'ratchet_rift',
    title: 'Ratchet & Clank: Rift Apart',
    price: 1499,
    originalPrice: 3999,
    discount: 62,
    rating: 4.8,
    image: getSteamImage('1895880'),
    video: 'https://www.youtube.com/embed/ai3o0XtrnM8',
    platform: 'Steam',
    genre: 'Platformer',
    releaseDate: '2023-07-26',
    players: 'Single-player',
    description: 'Blast your way through an interdimensional adventure.',
    systemReq: SPECS_HIGH,
    reviews: []
  },
  {
    id: 'sf6',
    title: 'Street Fighter 6',
    price: 1999,
    originalPrice: 4999,
    discount: 60,
    rating: 4.8,
    image: getSteamImage('1364780'),
    video: 'https://www.youtube.com/embed/2v75C6Q6h_Q',
    platform: 'Steam',
    genre: 'Fighting',
    releaseDate: '2023-06-02',
    players: 'Multiplayer',
    description: 'Here comes a new challenger! The next evolution of the Street Fighter series.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'diablo4',
    title: 'Diablo® IV',
    price: 2499,
    originalPrice: 5599,
    discount: 55,
    rating: 4.2,
    image: getSteamImage('2344520'),
    video: 'https://www.youtube.com/embed/Ro26B394ZBM',
    platform: 'BattleNet',
    genre: 'Action RPG',
    releaseDate: '2023-06-05',
    players: 'Multiplayer',
    description: 'The endless battle between the High Heavens and the Burning Hells continues.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'jedi_survivor',
    title: 'Star Wars Jedi: Survivor™',
    price: 1999,
    originalPrice: 4499,
    discount: 55,
    rating: 4.4,
    image: getSteamImage('1774580'),
    video: 'https://www.youtube.com/embed/VRaobDJjIEC',
    platform: 'Steam',
    genre: 'Action Adventure',
    releaseDate: '2023-04-28',
    players: 'Single-player',
    description: 'The story of Cal Kestis continues in Star Wars Jedi: Survivor™.',
    systemReq: SPECS_HIGH,
    reviews: []
  },
  {
    id: 'tlou_part1',
    title: 'The Last of Us™ Part I',
    price: 1999,
    originalPrice: 3999,
    discount: 50,
    rating: 4.8,
    image: getSteamImage('1888930'),
    video: 'https://www.youtube.com/embed/WxjeV10H1F0',
    platform: 'Steam',
    genre: 'Adventure',
    releaseDate: '2023-03-28',
    players: 'Single-player',
    description: 'Experience the emotional storytelling and unforgettable characters in The Last of Us.',
    systemReq: SPECS_HIGH,
    reviews: []
  },
  {
    id: 'resident_evil_4',
    title: 'Resident Evil 4 Remake',
    price: 1599,
    originalPrice: 3599,
    discount: 55,
    rating: 4.9,
    image: getSteamImage('2050650'),
    video: 'https://www.youtube.com/embed/IdtzqC5uOqA',
    platform: 'Steam',
    genre: 'Horror',
    releaseDate: '2023-03-24',
    players: 'Single-player',
    description: 'Survival is just the beginning. The classic reborn with modernized gameplay.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'hogwarts_legacy',
    title: 'Hogwarts Legacy',
    price: 1499,
    originalPrice: 2999,
    discount: 50,
    rating: 4.7,
    image: getSteamImage('990080'),
    video: 'https://www.youtube.com/embed/1O6QstnCpB4',
    platform: 'Steam',
    genre: 'Open World RPG',
    releaseDate: '2023-02-10',
    players: 'Single-player',
    description: 'Live the unwritten. Your acceptance letter to Hogwarts has finally arrived.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'dead_space',
    title: 'Dead Space',
    price: 1599,
    originalPrice: 3999,
    discount: 60,
    rating: 4.8,
    image: getSteamImage('1693980'),
    video: 'https://www.youtube.com/embed/ctvYh8l1tJA',
    platform: 'Steam',
    genre: 'Horror',
    releaseDate: '2023-01-27',
    players: 'Single-player',
    description: 'The sci-fi survival horror classic returns, completely rebuilt.',
    systemReq: SPECS_HIGH,
    reviews: []
  },

  // --- 2022 HITS ---
  {
    id: 'gow_ragnarok_ps5',
    title: 'God of War Ragnarök',
    price: 2999,
    originalPrice: 5999,
    discount: 50,
    rating: 5.0,
    image: 'https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png',
    video: 'https://www.youtube.com/embed/hfJ4Km46A-0',
    platform: 'PS5',
    genre: 'Action',
    releaseDate: '2022-11-09',
    players: 'Single-player',
    description: 'Kratos and Atreus must journey to each of the Nine Realms in search of answers.',
    systemReq: SPECS_HIGH,
    reviews: []
  },
  {
    id: 'mw2_2022',
    title: 'Call of Duty®: MW II',
    price: 1999,
    originalPrice: 4999,
    discount: 60,
    rating: 4.0,
    image: getSteamImage('1938090'),
    video: 'https://www.youtube.com/embed/OeVapCrI1pY',
    platform: 'Steam',
    genre: 'FPS',
    releaseDate: '2022-10-28',
    players: 'Multiplayer',
    description: 'Welcome to the new era of Call of Duty®.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'uncharted_legacy',
    title: 'UNCHARTED™: Legacy of Thieves',
    price: 1199,
    originalPrice: 3299,
    discount: 63,
    rating: 4.7,
    image: getSteamImage('1659420'),
    video: 'https://www.youtube.com/embed/I0tX8qXfVl0',
    platform: 'Steam',
    genre: 'Adventure',
    releaseDate: '2022-10-19',
    players: 'Single-player',
    description: 'Seek your fortune and leave your mark on the map in the UNCHARTED collection.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'spiderman_remastered',
    title: 'Marvel\'s Spider-Man Remastered',
    price: 1599,
    originalPrice: 3999,
    discount: 60,
    rating: 4.9,
    image: getSteamImage('1817070'),
    video: 'https://www.youtube.com/embed/K4tmT7279tI',
    platform: 'Steam',
    genre: 'Action',
    releaseDate: '2022-08-12',
    players: 'Single-player',
    description: 'Play as Peter Parker fighting big crime and iconic villains in Marvel’s New York.',
    systemReq: SPECS_HIGH,
    reviews: []
  },
  {
    id: 'stray',
    title: 'Stray',
    price: 999,
    originalPrice: 1999,
    discount: 50,
    rating: 4.9,
    image: getSteamImage('1332010'),
    video: 'https://www.youtube.com/embed/u84hRUQlaio',
    platform: 'Steam',
    genre: 'Adventure',
    releaseDate: '2022-07-19',
    players: 'Single-player',
    description: 'Lost, alone and separated from family, a stray cat must untangle an ancient mystery.',
    systemReq: SPECS_LOW,
    reviews: []
  },
  {
    id: 'elden_ring',
    title: 'ELDEN RING',
    price: 1999,
    originalPrice: 3599,
    discount: 45,
    rating: 5.0,
    image: getSteamImage('1245620'),
    video: 'https://www.youtube.com/embed/E3Huy2cdih0',
    platform: 'Steam',
    genre: 'Open World RPG',
    releaseDate: '2022-02-25',
    players: 'Co-op',
    description: 'THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'god_of_war_pc',
    title: 'God of War (2018)',
    price: 1199,
    originalPrice: 3299,
    discount: 63,
    rating: 4.9,
    image: getSteamImage('1593500'),
    video: 'https://www.youtube.com/embed/AN3jEjjcTV4',
    platform: 'Steam',
    genre: 'Action',
    releaseDate: '2022-01-14',
    players: 'Single-player',
    description: 'His vengeance against the Gods of Olympus years behind him, Kratos now lives as a man.',
    systemReq: SPECS_MID,
    reviews: []
  },

  // --- 2021 HITS ---
  {
    id: 'halo_infinite',
    title: 'Halo Infinite (Campaign)',
    price: 1499,
    originalPrice: 4999,
    discount: 70,
    rating: 4.2,
    image: getSteamImage('1240440'),
    video: 'https://www.youtube.com/embed/PyMlV5_HRWk',
    platform: 'Steam',
    genre: 'FPS',
    releaseDate: '2021-12-08',
    players: 'Single-player',
    description: 'When all hope is lost, the Master Chief is ready to confront the most ruthless foe.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'forza_horizon_5',
    title: 'Forza Horizon 5',
    price: 1299,
    originalPrice: 3499,
    discount: 62,
    rating: 4.9,
    image: getSteamImage('1551360'),
    video: 'https://www.youtube.com/embed/FYH9n37B7Yw',
    platform: 'Steam',
    genre: 'Racing',
    releaseDate: '2021-11-09',
    players: 'Multiplayer',
    description: 'Your Ultimate Horizon Adventure awaits! Explore the vibrant landscapes of Mexico.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'farcry6',
    title: 'Far Cry 6',
    price: 899,
    originalPrice: 2999,
    discount: 70,
    rating: 4.4,
    image: getSteamImage('2369390'),
    video: 'https://www.youtube.com/embed/-I0t5Z20e40',
    platform: 'Ubisoft',
    genre: 'FPS',
    releaseDate: '2021-10-07',
    players: 'Co-op',
    description: 'Welcome to Yara, a tropical paradise frozen in time. Join the revolution.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'resident_evil_village',
    title: 'Resident Evil Village',
    price: 999,
    originalPrice: 2999,
    discount: 66,
    rating: 4.8,
    image: getSteamImage('1196590'),
    video: 'https://www.youtube.com/embed/btFclZUXpzA',
    platform: 'Steam',
    genre: 'Horror',
    releaseDate: '2021-05-07',
    players: 'Single-player',
    description: 'Experience survival horror like never before in the eighth major installment.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'it_takes_two',
    title: 'It Takes Two',
    price: 899,
    originalPrice: 2199,
    discount: 59,
    rating: 5.0,
    image: getSteamImage('1426210'),
    video: 'https://www.youtube.com/embed/ohClxMmNLQQ',
    platform: 'Steam',
    genre: 'Co-op',
    releaseDate: '2021-03-26',
    players: 'Co-op',
    description: 'Embark on the craziest journey of your life in It Takes Two.',
    systemReq: SPECS_MID,
    reviews: []
  },

  // --- 2020 CLASSICS ---
  {
    id: 'cyberpunk_2077',
    title: 'Cyberpunk 2077',
    price: 1499,
    originalPrice: 2999,
    discount: 50,
    rating: 4.8,
    image: getSteamImage('1091500'),
    video: 'https://www.youtube.com/embed/8X2kIfS6fb8',
    platform: 'Steam',
    genre: 'Open World RPG',
    releaseDate: '2020-12-10',
    players: 'Single-player',
    description: 'Cyberpunk 2077 is an open-world, action-adventure RPG set in the dark future of Night City.',
    systemReq: SPECS_HIGH,
    reviews: []
  },
  {
    id: 'ac_valhalla',
    title: 'Assassin\'s Creed Valhalla',
    price: 999,
    originalPrice: 2999,
    discount: 67,
    rating: 4.7,
    image: getSteamImage('2208920'),
    video: 'https://www.youtube.com/embed/ssrNcwxALS4',
    platform: 'Ubisoft',
    genre: 'Open World RPG',
    releaseDate: '2020-11-10',
    players: 'Single-player',
    description: 'Become Eivor, a legendary Viking raider. Explore England\'s Dark Ages.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'ghost_tsushima_ps4',
    title: 'Ghost of Tsushima (Original)',
    price: 999,
    originalPrice: 2499,
    discount: 60,
    rating: 4.9,
    image: 'https://image.api.playstation.com/vulcan/ap/rnd/202006/2311/p510006263566163353.png',
    video: 'https://www.youtube.com/embed/VT4shZb2jTc',
    platform: 'PS5',
    genre: 'Action',
    releaseDate: '2020-07-17',
    players: 'Single-player',
    description: 'A storm is coming. Venture into a vast open-world samurai adventure.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'tlou_part2',
    title: 'The Last of Us Part II',
    price: 1299,
    originalPrice: 2499,
    discount: 48,
    rating: 4.8,
    image: 'https://image.api.playstation.com/vulcan/ap/rnd/202311/1717/d69e4f4f7236526145610815162388656123011311516147.png',
    video: 'https://www.youtube.com/embed/qPNiIeKMHyg',
    platform: 'PS5',
    genre: 'Action Adventure',
    releaseDate: '2020-06-19',
    players: 'Single-player',
    description: 'Experience the escalating moral conflicts created by Ellie’s relentless pursuit of vengeance.',
    systemReq: SPECS_MID,
    reviews: []
  },
  {
    id: 'doom_eternal',
    title: 'DOOM Eternal',
    price: 799,
    originalPrice: 1999,
    discount: 60,
    rating: 4.9,
    image: getSteamImage('782330'),
    video: 'https://www.youtube.com/embed/_l3t26_gHQA',
    platform: 'Steam',
    genre: 'FPS',
    releaseDate: '2020-03-20',
    players: 'Single-player',
    description: 'Hell’s armies have invaded Earth. Become the Slayer.',
    systemReq: SPECS_MID,
    reviews: []
  },

  // --- UPCOMING BEASTS (2025-2026) ---
  {
    id: 'gta_vi_preorder',
    title: 'Grand Theft Auto VI',
    price: 6999,
    originalPrice: 7999,
    discount: 12,
    rating: 5.0,
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co83i0.jpg',
    video: 'https://www.youtube.com/embed/QdBZY2fkU-0',
    platform: 'PS5',
    genre: 'Open World',
    releaseDate: '2025-09-15',
    players: 'Multiplayer',
    description: 'PRE-ORDER NOW. Grand Theft Auto VI heads to the state of Leonida.',
    systemReq: SPECS_ULTRA,
    reviews: [],
    isNew: true
  },
  {
    id: 'death_stranding_2',
    title: 'Death Stranding 2: On The Beach',
    price: 4999,
    originalPrice: 5999,
    discount: 16,
    rating: 4.9,
    image: 'https://image.api.playstation.com/vulcan/ap/rnd/202402/0102/f17255132279269550302386221052601262332152555620.png',
    video: 'https://www.youtube.com/embed/AgpAi_zZJ7o',
    platform: 'PS5',
    genre: 'Action',
    releaseDate: '2025-05-20',
    players: 'Single-player',
    description: 'Sam Porter Bridges returns. Embark on a new mission to save humanity.',
    systemReq: SPECS_HIGH,
    reviews: [],
    isNew: true
  },
  {
    id: 'doom_dark_ages',
    title: 'DOOM: The Dark Ages',
    price: 4499,
    originalPrice: 4999,
    discount: 10,
    rating: 5.0,
    image: getSteamImage('3017860'),
    video: 'https://www.youtube.com/embed/4G2t32M9_m0',
    platform: 'Steam',
    genre: 'FPS',
    releaseDate: '2025-04-15',
    players: 'Single-player',
    description: 'Witness the origin of the Slayer\'s rage in this medieval warfare-inspired FPS prequel.',
    systemReq: SPECS_HIGH,
    reviews: [],
    isNew: true
  },
  {
    id: 'borderlands_4',
    title: 'Borderlands 4',
    price: 4299,
    originalPrice: 4999,
    discount: 14,
    rating: 4.6,
    image: getSteamImage('2854740'),
    video: 'https://www.youtube.com/embed/A6y2_h9x_x0',
    platform: 'Steam',
    genre: 'Looter Shooter',
    releaseDate: '2025-03-20',
    players: 'Co-op',
    description: 'The legendary looter shooter returns with a new planet, new hunters, and billions of guns.',
    systemReq: SPECS_MID,
    reviews: [],
    isNew: true
  }
];

// UPCOMING GAMES 2026/Future (Using Official Posters/Key Art)
export const UPCOMING_GAMES: UpcomingGame[] = [
  { 
    id: 'ghost_of_yotei', 
    title: 'Ghost of Yōtei', 
    releaseDate: '2025', 
    image: 'https://image.api.playstation.com/vulcan/ap/rnd/202409/2422/3f0862025401083416244670005713429302636294796013.png'
  },
  { 
    id: 'wolverine', 
    title: 'Marvel\'s Wolverine', 
    releaseDate: '2026', 
    image: 'https://cdn.marvel.com/content/1x/marvelswolverine_lob_crd_01.jpg' 
  },
  { 
    id: 'witcher_4', 
    title: 'The Witcher 4: Polaris', 
    releaseDate: 'Future', 
    image: 'https://static.cdprojektred.com/cms.cdprojektred.com/16x9_en.jpg' 
  },
  { 
    id: 'tes_vi', 
    title: 'The Elder Scrolls VI', 
    releaseDate: 'Future', 
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1q1f.jpg'
  },
  { 
    id: 'blade', 
    title: 'Marvel\'s Blade', 
    releaseDate: 'Future', 
    image: 'https://cdn.marvel.com/content/1x/marvelsblade_lob_crd_01.jpg'
  },
  { 
    id: 'star_wars_eclipse', 
    title: 'Star Wars Eclipse', 
    releaseDate: 'Future', 
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co49wa.jpg'
  },
  { 
    id: 'mass_effect_5', 
    title: 'Mass Effect 5', 
    releaseDate: 'Future', 
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2lbd.jpg'
  },
  { 
    id: 'phantom_blade_zero', 
    title: 'Phantom Blade Zero', 
    releaseDate: 'TBA', 
    image: 'https://image.api.playstation.com/vulcan/ap/rnd/202406/0702/09b788730953110292723023250275525506076326090757.png'
  },
  {
    id: 'physint',
    title: 'Physint (Hideo Kojima)',
    releaseDate: 'Future', 
    image: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co7l8j.jpg'
  }
];
